# Generated by Django 2.2.8 on 2020-03-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20200320_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='parent_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsapp.PostModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='parent_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='newsapp.CategoryModel'),
            preserve_default=False,
        ),
    ]
