# Generated by Django 2.2.8 on 2020-03-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20200320_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='parent_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='parent_category',
            new_name='category',
        ),
    ]
