# Generated by Django 2.2.8 on 2020-03-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20200320_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
